# Generated by Django 5.1.6 on 2025-02-18 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('contact_person', models.CharField(max_length=250)),
                ('company_email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=250)),
                ('company_phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=250)),
                ('support_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Junk', 'Junk'), ('Hot', 'Hot'), ('New', 'New')], default='New', max_length=50)),
                ('technical_details', models.CharField(choices=[('Test Passed', 'Test Passed'), ('Test Initiated', 'Test Initiated'), ('Test Fail', 'Test Fail'), ('Pending', 'Pending')], default='Test Initiated', max_length=50)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=50)),
                ('user_type', models.CharField(choices=[('Client', 'Client'), ('Vendor', 'Vendor')], default='Client', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyrecords.company')),
            ],
        ),
        migrations.CreateModel(
            name='SwitchIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=250, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyrecords.company')),
            ],
        ),
    ]
