# Generated by Django 5.1.6 on 2025-02-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyrecords', '0003_company_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
